[package]
name = "amm_governance"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cubit = { git = "https://github.com/influenceth/cubit.git", commit = "62756082bf2555d7ab25c69d9c7bc30574ff1ce8" }
konoha = { git = "https://github.com/carmineoptions/konoha", branch = "staking" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }
starknet = ">=2.0.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.23.0" }

[[target.starknet-contract]]
build-external-contracts = ["konoha::treasury::Treasury"]

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "MAINNET"
url = "$MAINNET_NODE_URL"
block_id.tag = "Latest"

[[tool.snforge.fork]]
name = "MAINNET_BEFORE_UPGRADE_TO_KONOHA"
url = "$MAINNET_NODE_URL"
block_id.number = "652000"

[[tool.snforge.fork]]
name = "MAINNET_ADD_EKUBO_POOLS"
url = "$MAINNET_NODE_URL"
block_id.number = "818610"

[[tool.snforge.fork]]
name = "MAINNET_UPGRADE_REMUS"
url = "$MAINNET_NODE_URL"
block_id.number = "1228005"

[[tool.snforge.fork]]
name = "SEPOLIA"
url = "$SEPOLIA_NODE_URL"
block_id.tag = "Latest"
