[package]
name = "amm_governance"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
konoha = { git = "https://github.com/carmineoptions/konoha", branch = "remove-carmine" }

[[target.starknet-contract]]

[tool.fmt]
sort-module-level-items = true
